
typedef struct
{
	char* buf;
	int len;
} reply_t;
reply_t libredis_call(const char *cmdbuf, int len);
void *libredis_new_instance(const char* load_filename, int argc, char **argv);
void libredis_set_instance(void* pinst);
//I don't want to read the implementation of modified malloc at all.
//User should simpley call this function to free the reply generated by libredis_call.
void libredis_drop_reply(reply_t *reply);
int libredis_save(const char* filename);